### ISSUE TITLE
Viterbi alignment crashes

### ISSUE THREAD

**Issue by alaindesilets** [loomchild/maligna#6]
[faulty-files.zip](https://github.com/loomchild/maligna/files/5454188/faulty-files.zip)

The alignment algorithm crashes when I run it on the files in the attached zip file.

The sequence of commands I do is:

`   Running Maligna command: -c txt l1.sents l2.sents`
`   Running Maligna command: -c split-sentence`
`   Running Maligna command: -c trim`
`   unning Maligna command: -c viterbi -a poisson one-to-one -n word -s iterative-band`

and here is the stacktrace:

java.lang.AssertionError
	at net.loomchild.maligna.progress.WriterProgressObserver.updateIndex(WriterProgressObserver.java:56)
	at net.loomchild.maligna.progress.WriterProgressObserver.completeTask(WriterProgressObserver.java:51)
	at net.loomchild.maligna.progress.ProgressManager.completeTask(ProgressManager.java:85)
	at net.loomchild.maligna.progress.ProgressMeter.completeTasks(ProgressMeter.java:100)
	at net.loomchild.maligna.progress.ProgressMeter.completeTask(ProgressMeter.java:87)
	at net.loomchild.maligna.filter.aligner.align.hmm.viterbi.ViterbiAlgorithm.align(ViterbiAlgorithm.java:89)
	at net.loomchild.maligna.filter.aligner.align.hmm.adaptive.AdaptiveBandAlgorithm.align(AdaptiveBandAlgorithm.java:137)
	at net.loomchild.maligna.filter.aligner.Aligner.apply(Aligner.java:36)
	at net.loomchild.maligna.filter.meta.IgnoreInfiniteProbabilityAlignmentsFilterDecorator.apply(IgnoreInfiniteProbabilityAlignmentsFilterDecorator.java:52)
	at net.loomchild.maligna.ui.console.command.AlignCommand.run(AlignCommand.java:120)
	at net.loomchild.maligna.ui.console.command.AbstractCommand.run(AbstractCommand.java:104)
	at ca.pirurvik.iutools.concordancer.Aligner_Maligna.run(Aligner_Maligna.java:164)
	at ca.pirurvik.iutools.concordancer.Aligner_Maligna.run(Aligner_Maligna.java:128)
	at ca.pirurvik.iutools.concordancer.Aligner_Maligna.align(Aligner_Maligna.java:52)
	at ca.pirurvik.iutools.concordancer.Aligner_Maligna.align(Aligner_Maligna.java:39)
	at ca.pirurvik.iutools.concordancer.WebConcordancer.alignContents(WebConcordancer.java:210)
	at ca.pirurvik.iutools.concordancer.WebConcordancer.alignPage(WebConcordancer.java:72)
	at ca.pirurvik.iutools.concordancer.WebConcordancerTest.test__alignPage__HappyPath(WebConcordancerTest.java:95)

**Comment by loomchild** [comment]
There seems to be an issue with progress reporter (the thing that shows how much of the document has already been processed). Weird, I will try to look into this in coming days.

Note that your command line looks wrong - one-to-one to is an option to select command, not align (see examples in README). Perhaps this is the culprit...

You can also try disabling progress reporter via `-v quiet` option, although not sure if it will help.
